### ISSUE TITLE
Credentials are passed to Nexus

### ISSUE THREAD

**Issue by shochdoerfer** [sonatype/bower-nexus3-resolver#8]
Given I have a .bowerrc file like this:
```js
{
  "registry" : {
    "search" : [ "https://nexus3.loc/repository/bower" ],
    "register" : "https://nexus3.loc/repository/bower-releases/"
   },
  "nexus" : {
    "username" : "my_user",
    "password" : "my_pass"
  },
  "resolvers" : [ "bower-nexus3-resolver" ]
}
```

Then trying to run a bower install command the username and password seem not to be sent to Nexus. The only way I am able to send the credentials to Nexus is to add them to the search and register urls:

```js
{
  "registry" : {
    "search" : [ "my_user:my_pass@https://nexus3.loc/repository/bower" ],
    "register" : "my_user:my_pass@https://nexus3.loc/repository/bower-releases/"
   },
  "nexus" : {
    "username" : "my_user",
    "password" : "my_pass"
  },
  "resolvers" : [ "bower-nexus3-resolver" ]
}
```
Am I doing anything wrong?

**Comment by fjmilens3** [comment]
No, what you're doing in your second example is actually the correct approach, and our documentation on this was incorrect when we initially released. 

If you're interested in further details, continue on:

1. The username and password must be provided in the search and register urls. These credentials are used by the bower client itself when it connects to Nexus and accesses the registry.
2. The username and password must *also* be provided in the special "nexus" section. These credentials are used by the bower-nexus3-resolver when it actually pulls down the archive for what you're trying to install.

(One way to think about it is not unlike if you were accessing a secured Bower registry that referenced a secured Git repo. You'd have credentials to access the registry, and then you'd have your Git credentials to access the Git repo. That said, as a developer myself, I can sympathize that this can be a bit less than ideal.)

**Comment by shochdoerfer** [comment]
Got it. Isn't there a way that would allow you to set the credentials from the special "nexus" section for the search and register urls when doing the respective requests? Like passing additional header information when doing the requests?

I mean it's fine for me but still looks a bit wired to define the credentials twice in different contexts.

**Comment by fjmilens3** [comment]
It is, but unfortunately it's not as obvious a mapping between the two as one might hope, largely because Nexus is trying to be two things at once from the standpoint of the Bower ecosystem. They're quite distinct even though Nexus is acting as both. Fundamentally, Bower is a registry that takes a name and points you to a specific url to download that thing. Various resolvers exist to determine what that url represents and how to obtain the other information it needs (versions, downloadable archives), and for most people this resolver will use some kind of version control, Github or Bitbucket for example.

The Bower pluggable resolver API (https://bower.io/docs/pluggable-resolvers), which is something provided by Bower to allow the kind of integration to other systems that Nexus is doing, only deals with determining versions and fetching packages. It is not responsible for the initial request to the search URLs. This makes perfect sense from the Bower standpoint as it's agnostic to how something is to be retrieved, and most of what Bower does is provide a standardized registry not unlike a phone book. The Bower API doesn't provide any way to provide blanket usage of credentials for all requests, nor should it, since retrieval of versions and packages is distinct from looking up where they reside. Nor does it provide the username and password for the registry request to the resolver when it's fetching it, as under normal circumstances these would be two completely separate concerns (why would your Github credentials be the same as those you're using to access a Bower private registry, for example?). It's only in the special case of a solution like Nexus, as implemented, that you'd really have the possibility of shared credentials for both kinds of request in the first place.

None of this is to say that you couldn't in theory hack something together so that the pluggable resolver could get the credentials in some way. One alternative that we considered during development was to examine the Bower configuration that was provided to the resolver, attempt to match up the base urls for our requests to the base urls for the search urls in the Bower configuration, and then extract the username and password from the match. However, that involves implicit behavior that's a bit magical in terms of not being directly obvious what it's doing, and definitely blurs the separation of concerns inherent to the Bower model. In the end, we decided to keep it simple and require separate credentials specifically for Nexus rather than conflate the two.

**Comment by shochdoerfer** [comment]
Bonus points for the in-depth coverage @fjmilens3 ;) Totally makes sense, so feel free to close the issue. As long as the behavior is documented now I am fine.

**Comment by fjmilens3** [comment]
I will ask @joedragons or @dulanism to confirm that we did in fact update the documentation, but will consider this issue closed. Thanks for getting in touch!
